name: validate
on: [push, pull_request]

permissions:
  contents: read

jobs:
  linters:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
          # TODO use --out-format=junit-xml and store artifacts
          args: --print-resources-usage --timeout=10m --verbose
